### ISSUE TITLE
Is there a provision to load test the 5G Core deployed with onRamp using gnbSim ?

### ISSUE THREAD

**Issue by souravpaul8** [omec-project/gnbsim#217]
I want to calculate metrics like throughput and response time, to test its performance

**Comment by thakurajayL** [comment]
You will not be able to do data throughput, but you will be able to load 5G Core with many more subscribers and run the iterations of supported procedures. We know how data can be supported but due to limited bandwidth not able to support all required features. Will you be interested in contributing the feature?

**Comment by thakurajayL** [comment]
Hi @souravpaul8  - do you have further comments?

**Comment by souravpaul8** [comment]
@thakurajayL Once I get some bandwidth, will surely be interested in contributing this feature.
